#!/bin/bash
set -euo pipefail

# https://stackoverflow.com/a/246128
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

main() {
  local api_key="${BUILDKITE_PLUGIN_CREATE_DATADOG_EVENT_API_KEY}"
  local datadog_host="${BUILDKITE_PLUGIN_CREATE_DATADOG_EVENT_DATADOG_HOST:-https://api.datadoghq.com}"
  local payload_body

  if [[ -z "$api_key" ]]; then
    echo "no API key was provided"
    exit 1
  fi

  payload_body="$(make_body)"

  curl -fsS -X POST \
    -H "Content-type: application/json" \
    -H "DD-API-KEY: ${api_key}" \
    -d "$payload_body" \
    "${datadog_host}/api/v1/events"
}

make_body() {
  if command -v python3 >/dev/null; then
    python3 "$DIR/construct_payload.py"
  else
    python "$DIR/construct_payload.py"
  fi
}

main
